default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Upload to Testflight"
  lane :upload_testflight do
    # Get the version number from the project and check against
    # the latest build already available on TestFlight, then
    # increase the build number by 1. If no build is available
    # for that version, then start at 1
   build_number = latest_testflight_build_number + 1 # Get build number
    increment_build_number_in_plist({                          # Increment build number
        build_number: build_number.to_s
    })      
    # Set up Distribution code signing and build the app
    match(type: "appstore")
    gym()
    # Upload the binary to TestFlight and automatically publish
    # to the configured beta testing group
    pilot(
      distribute_external: true,
      notify_external_testers: true
    )
  end
end
