source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'HelloToTheUniverse' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloToTheUniverse

  target 'HelloToTheUniverseTests' do
    inherit! :search_paths
    # Pods for testing
       pod 'Quick'
       pod 'Nimble'
  end
  
end
